# Generated by Django 4.2.16 on 2025-05-09 21:45

import aap_eda.core.utils.crypto.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import aap_eda.core.enums
import aap_eda.core.models.mixins
# The source of truth for permissions data changed since this migration
# - actions available for model is defined in model Meta properties
# - models tracked by role permissions added to permission_registry.register()
PERMISSIONS = {
    "credential_input_source": ["create", "read", "update", "delete"],
}


def insert_permissions(apps, schema_editor):
    import pdb
    pdb.set_trace()
    permission_model = apps.get_model("core", "Permission")
    db_alias = schema_editor.connection.alias
    permissions = []
    for resource_type, actions in PERMISSIONS.items():
        for action in actions:
            permissions.append(
                permission_model(resource_type=resource_type, action=action)
            )
    permission_model.objects.using(db_alias).bulk_create(permissions)


def drop_permissions(apps, schema_editor):
    permission_model = apps.get_model("core", "Permission")  # noqa: N806
    db_alias = schema_editor.connection.alias
    for resource_type, actions in PERMISSIONS.items():
        permission_model.objects.using(db_alias).filter(
            resource_type=resource_type, action__in=actions
        ).delete()
class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_remove_decisionenvironment_credential_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialInputSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("input_field_name", models.CharField(max_length=1024)),
                (
                    "metadata",
                    aap_eda.core.utils.crypto.fields.EncryptedTextField(
                        blank=True, default=""
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%s(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%s(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "source_credential",
                    models.ForeignKey(
                        help_text="External credential",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_input_sources",
                        to="core.edacredential",
                    ),
                ),
                (
                    "target_credential",
                    models.ForeignKey(
                        help_text="Non external credential",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_sources",
                        to="core.edacredential",
                    ),
                ),
            ],
            options={
                "db_table": "core_credential_input_source",
                "ordering": (
                    "target_credential",
                    "source_credential",
                    "input_field_name",
                ),
                "unique_together": {("target_credential", "input_field_name")},
            },
        ),
        #migrations.RunPython(insert_permissions, drop_permissions),
    ]
