# Generated by Django 5.2.9 on 2026-05-07 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0071_rename_eda_credential_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventstream",
            name="consumer_credential",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consumer_event_streams",
                to="core.edacredential",
            ),
        ),
        migrations.AddField(
            model_name="eventstream",
            name="producer_credential",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="producer_event_streams",
                to="core.edacredential",
            ),
        ),
        migrations.AddField(
            model_name="eventstream",
            name="pubsub_kind",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The kind of pubsub that is used with this event stream",
            ),
        ),
    ]
