# Generated by Django 5.2.13 on 2026-05-01 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_rename_eda_credential_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="RulebookProcessHeartbeat",
            fields=[
                (
                    "process",
                    models.OneToOneField(
                        help_text="RulebookProcess with CASCADE delete for automatic cleanup",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.rulebookprocess",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Automatically updated on every save - used for liveness checks",
                    ),
                ),
                (
                    "stats",
                    models.JSONField(
                        default=dict,
                        help_text="Ruleset statistics: {ruleset_name: {eventsProcessed, rulesTriggered, ...}}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "core_rulebook_process_heartbeat",
                "indexes": [
                    models.Index(
                        fields=["updated_at"], name="idx_heartbeat_updated_at"
                    )
                ],
            },
        ),
    ]
