# Generated by Django 5.2.9 on 2026-07-04 14:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_activation_k8s_pod_tolerations"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivationNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this node",
                        unique=True,
                    ),
                ),
                (
                    "queue_name",
                    models.TextField(
                        help_text="Queue name from RULEBOOK_WORKER_QUEUES (read-only, set at creation)",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="User-friendly name for this node",
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of this node",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "core_activation_node",
                "ordering": ("queue_name",),
                "indexes": [
                    models.Index(
                        fields=["queue_name"], name="ix_node_queue_name"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="activation",
            name="activation_node",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Node where this activation should run (used for podman deployments, null for k8s)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activations",
                to="core.activationnode",
            ),
        ),
        migrations.CreateModel(
            name="HighAvailabilityGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID used for HA coordination across activation instances",
                        unique=True,
                    ),
                ),
                (
                    "service_stats",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Statistics about the group including current leader, member health, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%s(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%s(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "core_high_availability_group",
                "ordering": ("-created_at",),
                "default_permissions": ["add", "view", "change", "delete"],
            },
        ),
        migrations.AddField(
            model_name="activation",
            name="high_availability_group",
            field=models.ForeignKey(
                default=None,
                help_text="The HighAvailabilityGroup this activation belongs to for HA support. Multiple activations with the same group will coordinate as a high-availability group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activations",
                to="core.highavailabilitygroup",
            ),
        ),
        migrations.AddIndex(
            model_name="highavailabilitygroup",
            index=models.Index(fields=["name"], name="ix_ha_group_name"),
        ),
        migrations.AddIndex(
            model_name="highavailabilitygroup",
            index=models.Index(fields=["uuid"], name="ix_ha_group_uuid"),
        ),
    ]
